spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

resilience4j:
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        eventConsumerBufferSize: 100
    instances:
      couriers.saveCouriers:
        baseConfig: default
      couriers.readBy:
        baseConfig: default
      couriers.readAll:
        baseConfig: default
      couriers.readMetaInfo:
        baseConfig: default
      couriers.assignments:
        baseConfig: default
      orders.saveOrders:
        baseConfig: default
      orders.complete:
        baseConfig: default
      orders.readAll:
        baseConfig: default
      orders.readBy:
        baseConfig: default
      orders.assign:
        baseConfig: default