--liquibase formatted sql

--changeset zlpr:1
CREATE TABLE courier
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id INTEGER,
    CONSTRAINT pk_courier PRIMARY KEY (id)
);
--changeset zlpr:2
CREATE TABLE courier_type
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type        VARCHAR(255),
    rating      INTEGER,
    earning     INTEGER,
    weight      FLOAT                                    NOT NULL,
    orders      INTEGER                                  NOT NULL,
    regions     INTEGER                                  NOT NULL,
    time_first  INTEGER                                  NOT NULL,
    time_others INTEGER                                  NOT NULL,
    CONSTRAINT pk_courier_type PRIMARY KEY (id)
);
--changeset zlpr:3
CREATE TABLE delivery_hours
(
    order_id   INTEGER NOT NULL,
    start_time time WITHOUT TIME ZONE,
    end_time   time WITHOUT TIME ZONE
);
--changeset zlpr:4
CREATE TABLE group_order
(
    id            INTEGER NOT NULL,
    delivery_date date,
    courier_id    INTEGER,
    weight        FLOAT   NOT NULL,
    orders        INTEGER NOT NULL,
    regions       INTEGER NOT NULL,
    time_first    INTEGER NOT NULL,
    time_others   INTEGER NOT NULL,
    CONSTRAINT pk_group_order PRIMARY KEY (id)
);
--changeset zlpr:5
CREATE TABLE orders
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    weight         FLOAT,
    cost           INTEGER,
    completed_time TIMESTAMP WITHOUT TIME ZONE,
    status         VARCHAR(255),
    courier_id     INTEGER,
    group_order_id INTEGER,
    region         INTEGER,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);
--changeset zlpr:6
CREATE TABLE region
(
    courier_id INTEGER NOT NULL,
    region     INTEGER
);
--changeset zlpr:7
CREATE TABLE working_hours
(
    courier_id INTEGER NOT NULL,
    start_time time WITHOUT TIME ZONE,
    end_time   time WITHOUT TIME ZONE
);
--changeset zlpr:8
ALTER TABLE courier_type
    ADD CONSTRAINT uc_courier_type_type UNIQUE (type);
--changeset zlpr:9
ALTER TABLE courier
    ADD CONSTRAINT FK_COURIER_ON_TYPE FOREIGN KEY (type_id) REFERENCES courier_type (id);
--changeset zlpr:10
ALTER TABLE group_order
    ADD CONSTRAINT FK_GROUP_ORDER_ON_COURIER FOREIGN KEY (courier_id) REFERENCES courier (id);
--changeset zlpr:11
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_COURIER FOREIGN KEY (courier_id) REFERENCES courier (id);
--changeset zlpr:12
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_GROUP_ORDER FOREIGN KEY (group_order_id) REFERENCES group_order (id);
--changeset zlpr:13
ALTER TABLE delivery_hours
    ADD CONSTRAINT fk_delivery_hours_on_order FOREIGN KEY (order_id) REFERENCES orders (id);
--changeset zlpr:14
ALTER TABLE region
    ADD CONSTRAINT fk_region_on_courier FOREIGN KEY (courier_id) REFERENCES courier (id);
--changeset zlpr:15
ALTER TABLE working_hours
    ADD CONSTRAINT fk_working_hours_on_courier FOREIGN KEY (courier_id) REFERENCES courier (id);